name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Start Ansible Playbook
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yml
